write-step 'dsdfsdf sdf d'
write-Substep 'dsdfsdf sdf d'
write-Substep 'dsdfsdf sdf d'
Write-Execute 'echo abc'
Write-Execute 'echo abc'
Write-Warning "Warning !!!"
Write-Execute 'echo abc'
Write-Warning "Warning !!!"
write-Substep 'dsdfsdf sdf d'
Write-Execute 'echo abc'
Write-Attention 'sdfsdf sdf d'
Write-Execute 'echo abc' 
write-step 'dsdfsdf sdf d'
Write-Execute 'echo abc' 
Write-Execute 'echo abc' 
Write-Error "Error!!!"
Write-Warning "Warning !!!"
Write-Attention 'sdfsdf sdf d'
Write-Attention 'sdfsdf sdf d'
Write-Error "Error!!!1111"
Write-Execute 'echo abc' 
write-Substep 'dsdfsdf sdf d'
write-Substep 'dsdfsdf sdf d'
write-Substep 'dsdfsdf sdf d'
Write-Attention 'sdfsdf sdf d'
write-Substep 'dsdfsdf sdf d'
write-Substep 'dsdfsdf sdf d'
write-step 'dsdfsdf sdf d'
write-Substep 'dsdfsdf sdf d'
write-Substep 'dsdfsdf sdf d'
write-step 'dsdfsdf sdf d'
write-step 'dsdfsdf sdf d'