# https://github.com/sxyazi/yazi/blob/main/yazi-config/preset/keymap-default.toml
#
[[mgr.prepend_keymap]]
on   = "!"
for  = "windows"
run  = 'shell "pwsh.exe" --block'
desc = "Open PowerShell here"

# Tasks, same as 'w'
[[mgr.prepend_keymap]]
on = "<C-`>"
run = "tasks:show"
desc = "Show task manager"

[[mgr.prepend_keymap]]
on   = "<A-->"
run  = "hardlink"
desc = "Hardlink yanked files"

# to check later
# https://github.com/boydaihungst/file-extra-metadata.yazi
[[mgr.prepend_keymap]]
on   = [ "g", "i" ]
run  = '''shell --block -- exiftool -k "%1"'''
desc = "show file info with exiftool"

[[mgr.prepend_keymap]]
on   = "<Home>"
run  = "arrow top"
desc = "Go to top (same as gg)"

[[mgr.prepend_keymap]]
on   = "<End>"
run  = "arrow bot"
desc = "Go to bottom (same as G)"

## change dir
# switch driver dir: `g, space` type d: `enter`

## Open
# `shift+enter`: open with(`enter`: open)

[[mgr.prepend_keymap]]
on   = "<A-Enter>"
# run  = '''shell -- pwsh -NoProfile -NoLogo -NonInteractive -File "M:\Script\Pwsh\config\yazi\pwsh\properties.ps1" "%1"'''
# run  = '''shell --orphan -- "M:\Script\Pwsh\config\yazi\pwsh\properties.exe" --no-focus "%1"'''
# run  = '''shell --orphan -- "M:\Script\Pwsh\config\yazi\pwsh\properties.exe" "%1"'''
run  = '''shell --orphan -- M:\Script\Pwsh\config\yazi\apps\properties.exe %1'''
desc = "show file info with properties"

# show shell open with dialog
[[mgr.prepend_keymap]]
on   = "<A-o>"
run  = '''shell --orphan -- M:\Script\Pwsh\config\yazi\apps\openwithsh.exe %1'''
desc = "Open with..."

[[mgr.prepend_keymap]]
on   = "<C-o>"
# note: --block to open as modal dialog
run  = '''shell --orphan -- M:\Script\Pwsh\config\yazi\apps\openFileDialog.exe --title "Open File" %d'''
desc = "Open file dialog(drag/drop)"

[[mgr.prepend_keymap]]
on   = "<C-S-o>"
run  = '''shell --orphan -- M:\Script\Pwsh\config\yazi\apps\openFileDialog.exe --folder --title "Open Folder" %d'''
desc = "Open folder dialog(drag/drop)"
# same as --modern, so not used here
# [[mgr.prepend_keymap]]
# on   = "<S-f>"
# run  = "plugin show-context-menu"
# desc = "Show shell context menu (classic)"

[[mgr.prepend_keymap]]
on   = "<A-f>"
run  = 'plugin show-context-menu -- --modern'
desc = "Show shell context menu (modern/Win11)"

[[mgr.prepend_keymap]]
on   = "<S-f>"
run  = 'plugin show-context-menu -- --background'
desc = "Show folder background context menu (New, Paste, ...)"

[[mgr.prepend_keymap]]
on   = [ "<C-k>", "r" ]
run  = 'shell "explorer /select,\"%1\"" --orphan'
desc = "Reveal in Windows Explorer"

## Archive
[[mgr.prepend_keymap]]
on   = [ "c", "a", "a" ]
run  = "plugin compress"
desc = "Archive selected files"

[[mgr.prepend_keymap]]
on   = [ "c", "a", "p" ]
run  = "plugin compress -p"
desc = "Archive selected files (password)"

[[mgr.prepend_keymap]]
on   = [ "c", "a", "h" ]
run  = "plugin compress -ph"
desc = "Archive selected files (password+header)"

[[mgr.prepend_keymap]]
on   = [ "c", "a", "l" ]
run  = "plugin compress -l"
desc = "Archive selected files (compression level)"

[[mgr.prepend_keymap]]
on   = [ "c", "a", "u" ]
run  = "plugin compress -phl"
desc = "Archive selected files (password+header+level)"

## image zoom plugin
[[mgr.prepend_keymap]]
on   = "="
run  = "plugin zoom 1"
desc = "Zoom in hovered file"

[[mgr.prepend_keymap]]
on   = "+"
run  = "plugin zoom -1"
desc = "Zoom out hovered file"

[[mgr.prepend_keymap]]
on   = "<A-.>"
run  = "plugin jump-to-char"
desc = "Jump to char"

### Panel
[[mgr.prepend_keymap]]
on   = "<A-n>"
run  = "plugin toggle-pane min-parent"
desc = "Show or hide the navigation pane"

## Preview Panel
[[mgr.prepend_keymap]]
on   = "<A-p>"
run  = "plugin toggle-pane min-preview"
desc = "Show or hide the preview pane"

[[mgr.prepend_keymap]]
on   = "<A-S-p>"
run  = "plugin toggle-pane max-preview"
desc = "Maximize or restore the preview pane"

## Parent Panel
[[mgr.prepend_keymap]]
on  = "<A-Up>"
run = "plugin parent-arrow -1"

[[mgr.prepend_keymap]]
on  = "<A-Down>"
run = "plugin parent-arrow 1"

[[mgr.prepend_keymap]]
on = "<A-Left>" # default is H
run = "back"
desc = "Back to previous directory"
[[mgr.prepend_keymap]]
on = "<A-Right>" # default is L
run = "forward"
desc = "Forward to next directory"

## bookmarks
[[mgr.prepend_keymap]]
on = "["
run = "plugin whoosh jump_by_key"
desc = "Jump bookmark by key"

# Direct fuzzy search access
[[mgr.prepend_keymap]]
on = "}"
run = "plugin whoosh jump_by_fzf"
desc = "Direct fuzzy search for bookmarks"

# Basic bookmark operations
[[mgr.prepend_keymap]]
on = [ "]", "a" ]
run = "plugin whoosh save"
desc = "Add bookmark (hovered file/directory)"

[[mgr.prepend_keymap]]
on = [ "]", "A" ]
run = "plugin whoosh save_cwd"
desc = "Add bookmark (current directory)"

# Temporary bookmarks
[[mgr.prepend_keymap]]
on = [ "]", "t" ]
run = "plugin whoosh save_temp"
desc = "Add temporary bookmark (hovered file/directory)"

[[mgr.prepend_keymap]]
on = [ "]", "T" ]
run = "plugin whoosh save_cwd_temp"
desc = "Add temporary bookmark (current directory)"

# Jump to bookmarks
[[mgr.prepend_keymap]]
on = "<A-k>"
run = "plugin whoosh jump_key_k"
desc = "Jump directly to bookmark with key k"

[[mgr.prepend_keymap]]
on = [ "]", "f" ]
run = "plugin whoosh jump_by_fzf"
desc = "Jump bookmark by fzf(same as '}')"

# Delete bookmarks
[[mgr.prepend_keymap]]
on = [ "]", "d" ]
run = "plugin whoosh delete_by_key"
desc = "Delete bookmark by key"

[[mgr.prepend_keymap]]
on = [ "]", "D" ]
run = "plugin whoosh delete_by_fzf"
desc = "Delete bookmarks by fzf (use TAB to select multiple)"

[[mgr.prepend_keymap]]
on = [ "]", "C" ]
run = "plugin whoosh delete_all"
desc = "Delete all user bookmarks"

# Rename bookmarks
[[mgr.prepend_keymap]]
on = [ "]", "r" ]
run = "plugin whoosh rename_by_key"
desc = "Rename bookmark by key"

[[mgr.prepend_keymap]]
on = [ "]", "R" ]
run = "plugin whoosh rename_by_fzf"
desc = "Rename bookmark by fzf"
## end of Bookmark keymaps

[[mgr.prepend_keymap]]
on   = ["g", "r"]
run  = "plugin cd-git-root"
desc = "Go to git repo root"

[[mgr.prepend_keymap]]
on   = [ "c", "r" ]
run  = "plugin path-from-root"
desc = "Copies path from git root"


[[mgr.prepend_keymap]]
on   = "<C-y>"
run  = "plugin system-clipboard"
desc = "yank&copy to system clipboard"

