# https://github.com/sxyazi/yazi/blob/main/yazi-config/preset/keymap-default.toml
#
[[mgr.prepend_keymap]]
on   = "!"
for  = "windows"
run  = 'shell "pwsh.exe" --block'
desc = "Open PowerShell here"

# Tasks
[[mgr.prepend_keymap]]
on = "<C-`>"
run = "tasks:show"
desc = "Show task manager"

[[mgr.prepend_keymap]]
on   = "<A-->"
run  = "hardlink"
desc = "Hardlink yanked files"

[[mgr.prepend_keymap]]
on   = [ "c", "r" ]
run  = "plugin path-from-root"
desc = "Copies path from git root"

# to check later
# https://github.com/boydaihungst/file-extra-metadata.yazi
[[mgr.prepend_keymap]]
on   = [ "g", "i" ]
run  = '''shell --block -- exiftool -k "%1"'''
desc = "show file info with exiftool"

[[mgr.prepend_keymap]]
on   = "<A-Enter>"
# run  = '''shell -- pwsh -NoProfile -NoLogo -NonInteractive -File "M:\Script\Pwsh\config\yazi\pwsh\properties.ps1" "%1"'''
# run  = '''shell --orphan -- "M:\Script\Pwsh\config\yazi\pwsh\properties.exe" --no-focus "%1"'''
run  = '''shell --orphan -- "M:\Script\Pwsh\config\yazi\pwsh\properties.exe" "%1"'''
desc = "show file info with properties"

## Archive
[[mgr.prepend_keymap]]
on   = [ "c", "a", "a" ]
run  = "plugin compress"
desc = "Archive selected files"

[[mgr.prepend_keymap]]
on   = [ "c", "a", "p" ]
run  = "plugin compress -p"
desc = "Archive selected files (password)"

[[mgr.prepend_keymap]]
on   = [ "c", "a", "h" ]
run  = "plugin compress -ph"
desc = "Archive selected files (password+header)"

[[mgr.prepend_keymap]]
on   = [ "c", "a", "l" ]
run  = "plugin compress -l"
desc = "Archive selected files (compression level)"

[[mgr.prepend_keymap]]
on   = [ "c", "a", "u" ]
run  = "plugin compress -phl"
desc = "Archive selected files (password+header+level)"

## zoom
[[mgr.prepend_keymap]]
on   = "="
run  = "plugin zoom 1"
desc = "Zoom in hovered file"

[[mgr.prepend_keymap]]
on   = "+"
run  = "plugin zoom -1"
desc = "Zoom out hovered file"

[[mgr.prepend_keymap]]
on   = "<A-.>"
run  = "plugin jump-to-char"
desc = "Jump to char"

#[[mgr.prepend_keymap]]
#on   = "l"
#run  = "plugin smart-enter"
#desc = "Enter the child directory, or open the file"

### Panel
[[mgr.prepend_keymap]]
on   = "<A-n>"
run  = "plugin toggle-pane min-parent"
desc = "Show or hide the navigation pane"

## Preview Panel
[[mgr.prepend_keymap]]
on   = "<A-p>"
run  = "plugin toggle-pane min-preview"
desc = "Show or hide the preview pane"

[[mgr.prepend_keymap]]
on   = "<A-S-p>"
run  = "plugin toggle-pane max-preview"
desc = "Maximize or restore the preview pane"
## Parent Panel
[[mgr.prepend_keymap]]
on  = "<A-Up>"
run = "plugin parent-arrow -1"

[[mgr.prepend_keymap]]
on  = "<A-Down>"
run = "plugin parent-arrow 1"

[[mgr.prepend_keymap]]
on = "<A-Left>" # default is H
run = "back"
desc = "Back to previous directory"
[[mgr.prepend_keymap]]
on = "<A-Right>" # default is L
run = "forward"
desc = "Forward to next directory"