# default config: https://github.com/sxyazi/yazi/blob/ae4c138f49e00a64b478318ed9c7e9072fef8c52/yazi-config/preset/yazi-default.toml
[mgr]
linemode = "size_and_mtime"

[plugin]
prepend_fetchers = [
    { group = "git", url = "*", run = "git" },
    { group = "git", url = "*/", run = "git" },
]
append_previewers = [
    { url = "*", run = "file-extra-metadata" },
]
append_spotters = [
    { url = "*", run = "file-extra-metadata" },
]

[opener]

system_open_with = [
    { run = 'M:\Script\Pwsh\config\yazi\apps\openwithsh.exe %1', orphan = true, desc = "Open with...", for = "windows" },
]
# https://github.com/sxyazi/yazi/blob/ae4c138f49e00a64b478318ed9c7e9072fef8c52/yazi-config/preset/yazi-default.toml#L32
edit = [
    { run = '${EDITOR:-vi} "$@"', desc = "$EDITOR", block = true, for = "unix" },
    { run = 'code %s', orphan = true, desc = "code", for = "windows" },
    # { run = "code -w %s",       desc = "code (block)", for = "windows", block = true },
]

# default rule: https://github.com/sxyazi/yazi/blob/ae4c138f49e00a64b478318ed9c7e9072fef8c52/yazi-config/preset/yazi-default.toml#L66
[open]
prepend_rules = [
    # the first one is used when type 'enter' key.
    # `url = "*"` does not match dirs (`foo/`); without this, preset `*/` uses `edit` first (VS Code).
    { url = "*/", use = [ "edit", "system_open_with", "reveal", "open" ] }, # open is defined to by system default opener, it is in the default rules.
    { mime = "text/*", use = [ "edit", "system_open_with", "reveal" ] },
    { mime = "image/*", use = [ "open", "system_open_with", "reveal" ] },
    { mime = "{audio,video}/*", use = [ "play", "system_open_with", "reveal" ] },
    { mime = "application/{json,ndjson,javascript,wine-extension-ini}", use = [ "edit", "system_open_with", "reveal" ] },
    # Archive
	{ mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", use = [ "extract", "system_open_with", "reveal" ] },
	# Empty file
	{ mime = "inode/empty", use = [ "edit", "system_open_with", "reveal" ] },
	# Virtual file system
	{ mime = "vfs/{absent,stale}", use = "download" },
    { url = "*", use = [ "open", "system_open_with", "reveal" ] },
]

[preview]
# run after change: yazi --clear-cache
max_width = 1920 # 900 default
max_height = 1200 # 600 default
# https://github.com/sxyazi/yazi/blob/ae4c138f49e00a64b478318ed9c7e9072fef8c52/yazi-config/preset/yazi-default.toml#L140
# rules = [

# ]