$script:args = @(
  @{Aliases = 'f'; Name = '-filter-search'; Description = 'Show only items matching the current search query in the listing. This overrides the --no-filter-search option.' },
  @{Aliases = 'nf'; Name = '-no-filter-search'; Description = 'Show all items in the listing even when searching (default). This overrides the --filter-search option.' },
  @{Aliases = 'd'; Name = '-folders-only'; Description = 'Show only folders (and symlinks pointing to folders) in the listing. This overrides the --no-folders-only option.' },
  @{Aliases = 'nd'; Name = '-no-folders-only'; Description = 'Show both files and folders in the listing. This is the default view mode. This overrides the --folders-only option.' },
  @{Aliases = 's'; Name = '-case-sensitive'; Description = 'Enable case-sensitive search. This overrides the --ignore-case and --smart-case options. You can also change the case sensitivity mode while the program is running with the keyboard shortcut ALT+C.' },
  @{Aliases = 'i'; Name = '-ignore-case'; Description = 'Enable case-insensitive search. This overrides the --case-sensitive and --smart-case options. You can also change the case sensitivity mode while the program is running with the keyboard shortcut ALT+C.' },
  @{Aliases = 'sc'; Name = '-smart-case'; Description = 'Enable smart-case search. If the search query contains only lowercase letters, search case insensitively. Otherwise search case sensitively. This is the default search mode. This overrides the --case-sensitive and --ignore-case options. You can also change the case sensitivity mode while the program is running with the keyboard shortcut ALT+C.' },
  @{Aliases = 'g'; Name = '-gap-search'; Description = 'When searching, match items that start with the same character as the search query, but allow gaps between the search characters. For example, searching for "do" would match "DesktOp", "DOcuments", and "DOwnloads", while searching for "dt" would match "DeskTop" and "DocumenTs" but not "downloads", and searching for "es" would match none of the above. This is the default behavior. This overrides the --gap-search and --no-gap-search options. You can also change the search mode while the program is running with the keyboard shortcut CTRL+F.' },
  @{Aliases = 'ga'; Name = '-gap-search-anywhere'; Description = 'When searching, allow the search characters to appear anywhere in a file/folder name, possibly with gaps between them. For example, searching for "do" would match "DesktOp", "DOcuments", and  DOwnloads", while searching for "es" would match "dESktop" and "documEntS", but not "downloads". This overrides the --gap-search-from-start and --no-gap-search options. You can also change the search mode while the program is running with the keyboard hortcut CTRL+F.' },
  @{Aliases = 'n'; Name = '-no-gap-search'; Description = 'Disable gap-search. Match only consecutive characters from the beginning of the search query. For example, searching for "do" would match "DOcuments" and "DOwnloads", but not "desktop". This overrides the --gap-search and --gap-search-from-start options. You can also change the search mode while the program is running with the keyboard shortcut CTRL+F.' }
  @{Name = '-autocd-timeout'; Description = "<TIMEOUT or 'off'> If the current search matches only one folder, automatically change to that folder after this many milliseconds. If the value is 'off', automatic cding is disabled, and you have to manually enter the older. Setting the timeout to zero is not recommended, because it makes navigation confusing. [default: 200]" },
  @{Name = '-history-file' ; Description = "<FILE or ''> Save a history of visited folders in this file in JSON format. Should be an absolute path. Set to empty to disable saving history. If not provided, defaults to '`$CACHE_DIR/ tere/history.json', where `$CACHE_DIR is the cache directory, i.e. `$XDG_CACHE_HOME or ~/.cache. Note that the history file reveals parts of your folder structure if it can be read by someone else." },
  @{Name = '-mouse'; Description = "<'on' or 'off'> Enable mouse navigation. If enabled, you can browse by clicking around with the mouse. [default: off]" },
  @{Aliases = 'h'; Name = '-help'; Description = 'Print help information' },
  @{Aliases = 'V'; Name = '-version'; Description = 'Print version information' }
)